-- Run as ACCOUNTADMIN (trial OK)
USE ROLE ACCOUNTADMIN;

-- Role and user (optional demo role)
CREATE OR REPLACE ROLE MLP_DEMO_ROLE;
GRANT ROLE MLP_DEMO_ROLE TO ROLE ACCOUNTADMIN;

-- Warehouses (S/M/L for ingest/transform/demo)
CREATE OR REPLACE WAREHOUSE MLP_INGEST_WH WAREHOUSE_SIZE='SMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE OR REPLACE WAREHOUSE MLP_TRANSFORM_WH WAREHOUSE_SIZE='MEDIUM' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE OR REPLACE WAREHOUSE MLP_DEMO_WH WAREHOUSE_SIZE='LARGE' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;

-- Database and schemas
CREATE OR REPLACE DATABASE MLP_DEMO_DB;
CREATE OR REPLACE SCHEMA MLP_DEMO_DB.RAW;
CREATE OR REPLACE SCHEMA MLP_DEMO_DB.STAGE;
CREATE OR REPLACE SCHEMA MLP_DEMO_DB.CURATED;

-- Grant minimal access for demo role
GRANT USAGE ON DATABASE MLP_DEMO_DB TO ROLE MLP_DEMO_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE MLP_DEMO_DB TO ROLE MLP_DEMO_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE MLP_DEMO_DB TO ROLE MLP_DEMO_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE MLP_DEMO_DB TO ROLE MLP_DEMO_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE MLP_DEMO_DB TO ROLE MLP_DEMO_ROLE;
GRANT OPERATE, USAGE ON WAREHOUSE MLP_INGEST_WH TO ROLE MLP_DEMO_ROLE;
GRANT OPERATE, USAGE ON WAREHOUSE MLP_TRANSFORM_WH TO ROLE MLP_DEMO_ROLE;
GRANT OPERATE, USAGE ON WAREHOUSE MLP_DEMO_WH TO ROLE MLP_DEMO_ROLE;

