-- Run as ACCOUNTADMIN (trial OK)
USE ROLE ACCOUNTADMIN;

-- Role and user (optional demo role)
CREATE OR REPLACE ROLE DEMO_LAB_ROLE;
GRANT ROLE DEMO_LAB_ROLE TO ROLE ACCOUNTADMIN;

-- Warehouses (S/M/L for ingest/transform/demo)
CREATE OR REPLACE WAREHOUSE LAB_INGEST_WH WAREHOUSE_SIZE='SMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE OR REPLACE WAREHOUSE LAB_TRANSFORM_WH WAREHOUSE_SIZE='MEDIUM' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE OR REPLACE WAREHOUSE LAB_DEMO_WH WAREHOUSE_SIZE='LARGE' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;

-- Database and schemas
CREATE OR REPLACE DATABASE DEMO_LAB_DB;
CREATE OR REPLACE SCHEMA DEMO_LAB_DB.RAW;
CREATE OR REPLACE SCHEMA DEMO_LAB_DB.STAGE;
CREATE OR REPLACE SCHEMA DEMO_LAB_DB.CURATED;

-- Grant minimal access for demo role
GRANT USAGE ON DATABASE DEMO_LAB_DB TO ROLE DEMO_LAB_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DEMO_LAB_DB TO ROLE DEMO_LAB_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE DEMO_LAB_DB TO ROLE DEMO_LAB_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE DEMO_LAB_DB TO ROLE DEMO_LAB_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE DEMO_LAB_DB TO ROLE DEMO_LAB_ROLE;
GRANT OPERATE, USAGE ON WAREHOUSE LAB_INGEST_WH TO ROLE DEMO_LAB_ROLE;
GRANT OPERATE, USAGE ON WAREHOUSE LAB_TRANSFORM_WH TO ROLE DEMO_LAB_ROLE;
GRANT OPERATE, USAGE ON WAREHOUSE LAB_DEMO_WH TO ROLE DEMO_LAB_ROLE;

