-- Streams and Tasks pipeline (after-stream chaining)
-- Financial Services theme: trades, market events, positions
USE ROLE ACCOUNTADMIN;
USE DATABASE DEMO_LAB_DB;
USE SCHEMA DEMO_LAB_DB.RAW;

-- Streams on raw tables
CREATE OR REPLACE STREAM TRADES_RAW_STREAM ON TABLE TRADES_RAW;
CREATE OR REPLACE STREAM MARKET_EVENTS_RAW_STREAM ON TABLE MARKET_EVENTS_RAW;
CREATE OR REPLACE STREAM POSITIONS_RAW_STREAM ON TABLE POSITIONS_RAW;

-- Stage schema objects
USE SCHEMA DEMO_LAB_DB.STAGE;

-- TRADES_ENRICHED: trades joined with position context
CREATE OR REPLACE TABLE TRADES_ENRICHED (
  TRADE_ID STRING,
  ACCOUNT_ID STRING,
  SYMBOL STRING,
  TRADE_TS TIMESTAMP_NTZ,
  SIDE STRING,
  QUANTITY NUMBER,
  PRICE NUMBER(18,4),
  AMOUNT NUMBER(18,2),
  EXCHANGE STRING,
  STATUS STRING,
  AVG_MARKET_PRICE NUMBER(18,4),
  TOTAL_POSITION_QTY NUMBER,
  TOTAL_MARKET_VALUE NUMBER(18,2)
);

-- EVENTS_FLATTENED: market events with extracted attributes
CREATE OR REPLACE TABLE EVENTS_FLATTENED (
  EVENT_TS TIMESTAMP_NTZ,
  SYMBOL STRING,
  EVENT_TYPE STRING,
  EVENT_ATTR VARIANT
);

-- Snowpark proc will write into STAGE.*; tasks will call it
-- Task chain: task_enrich_trades (checks stream) -> task_publish_metrics (AFTER previous)
CREATE OR REPLACE TASK task_enrich_trades
  WAREHOUSE = LAB_TRANSFORM_WH
  SCHEDULE = '1 minute'
  WHEN SYSTEM$STREAM_HAS_DATA('DEMO_LAB_DB.RAW.TRADES_RAW_STREAM')
AS
  CALL DEMO_LAB_DB.PUBLIC.SP_ENRICH_TRADES();

-- Curated tables (live in CURATED schema)
USE SCHEMA DEMO_LAB_DB.CURATED;

-- TRADE_METRICS: aggregated trading activity
CREATE OR REPLACE TABLE TRADE_METRICS (
  TRADE_HOUR TIMESTAMP_NTZ,
  SYMBOL STRING,
  TRADE_COUNT NUMBER,
  TOTAL_VOLUME NUMBER,
  TOTAL_NOTIONAL NUMBER(18,2),
  AVG_PRICE NUMBER(18,4),
  BUY_COUNT NUMBER,
  SELL_COUNT NUMBER
);

-- All tasks in STAGE schema (task dependencies must share schema)
USE SCHEMA DEMO_LAB_DB.STAGE;

CREATE OR REPLACE TASK task_publish_metrics
  WAREHOUSE = LAB_TRANSFORM_WH
  AFTER task_enrich_trades
AS
  INSERT INTO DEMO_LAB_DB.CURATED.TRADE_METRICS
  SELECT
    DATE_TRUNC('hour', TRADE_TS) AS TRADE_HOUR,
    SYMBOL,
    COUNT(*) AS TRADE_COUNT,
    SUM(QUANTITY) AS TOTAL_VOLUME,
    SUM(AMOUNT) AS TOTAL_NOTIONAL,
    AVG(PRICE) AS AVG_PRICE,
    SUM(CASE WHEN SIDE = 'BUY' THEN 1 ELSE 0 END) AS BUY_COUNT,
    SUM(CASE WHEN SIDE = 'SELL' THEN 1 ELSE 0 END) AS SELL_COUNT
  FROM DEMO_LAB_DB.STAGE.TRADES_ENRICHED
  GROUP BY DATE_TRUNC('hour', TRADE_TS), SYMBOL;

-- Enable tasks (child first, then root)
ALTER TASK DEMO_LAB_DB.STAGE.task_publish_metrics RESUME;
ALTER TASK DEMO_LAB_DB.STAGE.task_enrich_trades RESUME;
