-- Streams and Tasks pipeline (after-stream chaining)
USE ROLE ACCOUNTADMIN;
USE DATABASE DEMO_LAB_DB;
USE SCHEMA DEMO_LAB_DB.RAW;

-- Streams on raw tables
CREATE OR REPLACE STREAM ORDERS_RAW_STREAM ON TABLE ORDERS_RAW;
CREATE OR REPLACE STREAM EVENTS_RAW_STREAM ON TABLE EVENTS_RAW;
CREATE OR REPLACE STREAM INVENTORY_RAW_STREAM ON TABLE INVENTORY_RAW;

-- Stage schema objects
USE SCHEMA DEMO_LAB_DB.STAGE;
CREATE OR REPLACE TABLE ORDERS_ENRICHED LIKE DEMO_LAB_DB.RAW.ORDERS_RAW;
CREATE OR REPLACE TABLE EVENTS_FLATTENED (
  EVENT_TS TIMESTAMP_NTZ,
  USER_ID STRING,
  EVENT_TYPE STRING,
  EVENT_ATTR VARIANT
);

-- Snowpark proc will write into STAGE.*; tasks will call it
-- Task chain: task_transform_stage (checks stream) -> task_publish_curated (AFTER previous)
CREATE OR REPLACE TASK task_transform_stage
  WAREHOUSE = LAB_TRANSFORM_WH
  SCHEDULE = '1 minute'
  WHEN SYSTEM$STREAM_HAS_DATA('DEMO_LAB_DB.RAW.ORDERS_RAW_STREAM')
AS
  CALL DEMO_LAB_DB.PUBLIC.SP_TRANSFORM_ORDERS();

-- Publish/curate step (simple example insert-select)
USE SCHEMA DEMO_LAB_DB.CURATED;
CREATE OR REPLACE TABLE ORDER_METRICS AS SELECT * FROM DEMO_LAB_DB.STAGE.ORDERS_ENRICHED WHERE 1=0;

CREATE OR REPLACE TASK task_publish_curated
  WAREHOUSE = LAB_TRANSFORM_WH
  AFTER task_transform_stage
AS
  INSERT INTO ORDER_METRICS
  SELECT * FROM DEMO_LAB_DB.STAGE.ORDERS_ENRICHED;

-- Enable tasks
ALTER TASK DEMO_LAB_DB.STAGE.task_transform_stage RESUME;
ALTER TASK DEMO_LAB_DB.CURATED.task_publish_curated RESUME;

