-- Cost and usage queries for demo warehouses/tasks
USE ROLE ACCOUNTADMIN;

-- Warehouse metering (credits)
SELECT
  WAREHOUSE_NAME,
  START_TIME,
  END_TIME,
  CREDITS_USED
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE WAREHOUSE_NAME IN ('LAB_INGEST_WH','LAB_TRANSFORM_WH','LAB_DEMO_WH')
ORDER BY START_TIME DESC
LIMIT 200;

-- Task activity and query cost visibility
SELECT
  QUERY_TEXT,
  WAREHOUSE_NAME,
  ROLE_NAME,
  START_TIME,
  END_TIME,
  CREDITS_USED_CLOUD_SERVICES,
  CREDITS_USED_COMPUTE
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE WAREHOUSE_NAME IN ('LAB_INGEST_WH','LAB_TRANSFORM_WH','LAB_DEMO_WH')
  AND START_TIME >= DATEADD('day', -1, CURRENT_TIMESTAMP())
ORDER BY START_TIME DESC
LIMIT 200;

